apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: "default"
spec:
  selector:
    matchLabels:
      app: "frontend"
  replicas: 1
  template:
    metadata:
      labels:
        app: "frontend"
    spec:
      containers:
          - image: ://amazonaws.com
          imagePullPolicy: Always
          name: "frontend"
          ports:
            - containerPort: 80
